version: '2'
services:
  crawler:
    build: .
    entrypoint: /go/bin/crawler
    links:
      - postgres
      - influxdb
    environment:
      - POSTGRES_DSN=host=postgres user=govelib dbname=govelib sslmode=disable password=govelib
      - INFLUXDB_URI=http://influxdb:8086
      - DB_AUTOMIGRATE=true
    links:
      - postgres
      - influxdb
  heatmap:
    build: .
    entrypoint: /go/bin/heatmap
    environment:
      - POSTGRES_DSN=host=postgres user=govelib dbname=govelib sslmode=disable password=govelib
      - INFLUXDB_URI=http://influxdb:8086
      - CITY=paris
      - DB_AUTOMIGRATE=true
    links:
      - postgres
      - influxdb
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=govelib
      - POSTGRES_USER=govelib
      - POSTGRES_DB=govelib
  influxdb:
    image: influxdb:0.13-alpine
  caddy-proxy:
      image: abiosoft/caddy
      #        restart: unless-stopped
      ports:
        - 0.0.0.0:8080:8080
      volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ./www:/www
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "10"
  chronograf:
    image: lukasmartinelli/chronograf
    ports:
      - "10000:10000"
    environment:
      - INFLUXDB_HOST=influxdb
    links:
      - influxdb
